# Numpy Functions

In [13]:
import numpy as np

In [14]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim) #dimension of an arry

[1 2 3 4 5]
1


In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
print(np.__version__)##numpy version

1.20.2


In [17]:
ar=np.array([[1,2,3],[4,5,6]])
print(ar)

[[1 2 3]
 [4 5 6]]


In [18]:
print(type(ar))
print(ar.ndim)

<class 'numpy.ndarray'>
2


In [19]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [22]:
print(a[0,1,1])
print(a[1,0,1])

5
2


In [24]:
print(a[0,1,1]+a[1,0,1])

7


In [25]:
print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [30]:
print(a[-1,-2,0])

1


In [35]:
print(a.dtype)#datatyoe of an array

int32


In [40]:
b=np.array([1,2,3,4],dtype='f')
print(b)
newb=b.astype('i')
print(newb)
print(newb.dtype)

[1. 2. 3. 4.]
[1 2 3 4]
int32


In [42]:
c=newb.copy()
print(c)
newb[0]=10
c[3]=100
print(newb)
print(c)

[1 2 3 4]
[10  2  3  4]
[  1   2   3 100]


In [46]:
d=c.view()
print(d)
c[3]=4
print(c)
print(d)
d[0]=5
print(c)
print(d)


[  1   2   3 100]
[1 2 3 4]
[1 2 3 4]
[5 2 3 4]
[5 2 3 4]


In [47]:
print(c.base)
print(d.base)

None
[5 2 3 4]


In [50]:
x=np.array([[1,2,3,4],[4,5,6,7]])
print(x.shape)

(2, 4)


In [51]:
newx=x.reshape(4,2)
print(newx)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [57]:
p=np.array([10,20,30,40])
for i in p:
    print(i)

10
20
30
40


In [63]:
arr1=np.array([1,2,3,5])
arr2=np.array([5,6,7,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 5 5 6 7 8]


In [69]:
ar=np.stack((arr1,arr2),axis=1)
print(ar)

[[1 5]
 [2 6]
 [3 7]
 [5 8]]


In [71]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 5 5 6 7 8]


In [73]:
#arr = np.vstack((arr1, arr2))
##print(arr)

In [75]:
ar=np.array_split(arr,3)
print(ar)

[array([[1, 2, 3, 5]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]


In [78]:
n=np.array([1,2,3,2,5,6,2,8,2])
m=np.where(n==2)
print(m)
z=np.where(n%2==0)
print(z)

(array([1, 3, 6, 8], dtype=int64),)
(array([1, 3, 5, 6, 7, 8], dtype=int64),)


In [79]:
print(np.sort(n))

[1 2 2 2 2 3 5 6 8]
